const data = {
  products: [
    {
      name: "Nike slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirt",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "a high quality shirt",
    },
    {
      name: "Adidas fit shirt",
      slug: "adidas-fit-shirt",
      category: "Shirt",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.7,
      numReviews: 15,
      description: "a high quality shirt",
    },
    {
      name: "Nike slim pant",
      slug: "nike-slim-pant",
      category: "Pant",
      image: "/images/p3.jpg",
      price: 150,
      countInStock: 20,
      brand: "Nike",
      rating: 4.2,
      numReviews: 7,
      description: "a high quality pant",
    },
    {
      name: "Adidas fit pant",
      slug: "Adidas-fit-pant",
      category: "Pant",
      image: "/images/p4.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 5,
      description: "a high quality pant",
    },
  ],
};
